version: '3.8'
services:
  postgres:
    image: postgres:14.0
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports: 
      - '5433:5432'
    volumes:
      - ./data/schema.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - ./data/seed.sql:/docker-entrypoint-initdb.d/seed_tables.sql

  app:
    depends_on:
      - postgres
    restart: unless-stopped
    build:
      context: ./
    volumes:
      - .:/app
    ports:
      - '3000:3000'